### ISSUE TITLE
Coverage 4.0 support

### ISSUE THREAD

**Issue by ionelmc** [pybee/duvet#3]
Seems some things were changed in 4.0:
```
Traceback (most recent call last):
  File "/usr/local/bin/duvet", line 7, in <module>
    from duvet.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/duvet/__main__.py", line 10, in <module>
    from duvet.view import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/duvet/view.py", line 14, in <module>
    from coverage.parser import CodeParser
ImportError: cannot import name CodeParser
```

**Comment by alexkahn** [comment]
+1

**Comment by lamenezes** [comment]
+1

**Comment by lamenezes** [comment]
this issue only exists when installing duvet from pip (pip install duvet)

I cloned the repo in my machine and installed it with "pip install -e /path/duvet" and it works perfectly with coverage 4.0

**Comment by alexkahn** [comment]
Good catch @lamenezes! I just installed an older version of coverage (3.7.x I think) but that works much better!

**Comment by oz123** [comment]
Time for a new 0.1.3 release? The version in pypi is outdated ...

**Comment by jkahn** [comment]
I still have this bug.  Duvet version not up to date on pip?

**Comment by freakboy3742** [comment]
@jkahn Correct - I haven't pushed out a release of Duvet for a while; my attention is elsewhere. In the meantime, installing from git is your best bet.
